jackas/asp/urls.py
from django.urls import path
from asp import views

urlpatterns = [
	path('personal_home',
		views.PersonalHome.as_view(),
		name='personal_home'),
	path('view_home',
		views.ViewHome.as_view(),
		name='view_home'),
	path('<int:id>/personal_info',
		views.PersonalInfo.as_view(),
		name='personal_info'),
	path('change_info',
		views.ChangeInfo.as_view(),
		name='change_info'),
	path('clinic_manager/<int:id>/home',
		views.CMViewItems.as_view(),
		name='clinic_manager-home'),
	path('clinic_manager/item_info/<int:id>',
		views.CMViewItemInfo.as_view()),
	path('clinic_manager/shipping_label/<int:id>',
		views.CMViewShippingLabel.as_view()),
	path('clinic_manager/construct_order', 
		views.CMConstructOrder.as_view(), 
		name='constructOrder'),
	path('clinic_manager/<int:id>/view_order',
		views.CMViewOrder.as_view(),
		name='clinic_manager-view_order'),
	path('clinic_manager/<int:id>/cancel_order/<int:orderid>',
		views.CMCancelOrder.as_view(),
		name='clinic_manager-cancel-order'),
	path('clinic_manager/<int:id>/confirm_order/<int:orderid>',
		views.CMConfirmOrder.as_view(),
		name='clinic_manager-confirm-order'),
	path('dispatcher/<int:id>/home',
		views.DispatcherViewQueue.as_view(),
		name='dispatcher-home'),
	path('dispatcher/<int:id>/dispatch_order',
		views.DispatcherViewPackage.as_view(),
		name='dispatcher-package'),
	path('dispatcher/generate_csv',
		views.DispatcherViewItinerary.as_view(),
		name='dispatcher-itinerary'),
	path('dispatcher/<int:id>/confirm_dispatch',
		views.DispatcherConfirmDispatch.as_view(),
		name='dispatcher-confirm'),
	path('warehouse_personnel/<int:id>/home',
		views.WarehousePersonnelHome.as_view(),
		name='wp-home'),
	path('warehouse_personnel/<int:id>/process_order',
		views.WarehousePersonnelProcessOrder.as_view(),
		name='wp-process-order'),
	path('warehouse_personnel/<int:id>/confirm_process',
		views.WarehousePersonnelConfirmOrder.as_view(),
		name='wp-confirm-process'),
	path('warehouse_personnel/generate_shipping_label',
		views.WarehousePersonnelGenerateSL.as_view(),
		name='wp-generate-sl'),
]

jackas/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('asp/', include('asp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name='homepage.html'), name='home'),
]

jackas/asp/models.py
from django.db import models

class Clinic(models.Model):
	clinic_name = models.CharField(max_length=100)
	clinic_address = models.CharField(max_length=200)
	distance_to_hospital = models.DecimalField(max_digits=10, decimal_places=6, default=0.000000)
	latitude = models.DecimalField(max_digits=10, decimal_places=6, default=0.000000)
	longitude = models.DecimalField(max_digits=10, decimal_places=6, default=0.000000)
	altitude = models.DecimalField(max_digits=10, decimal_places=6, default=0.000000)
	def __str__(self):
		return self.clinic_name

class User(models.Model):
	username = models.CharField(max_length=50)
	firstname = models.CharField(max_length=50)
	lastname = models.CharField(max_length=50)
	password = models.CharField(max_length=20)
	email = models.CharField(max_length=50)
	ROLE_CHOICES = (('CM', 'Clinic Manager'), ('WP', 'Warehouse Personnel'), ('D', 'Dispacher'))
	role = models.CharField(max_length=2, choices=ROLE_CHOICES, default='CM')
	clinic_id = models.ForeignKey(Clinic, on_delete=models.CASCADE, null=True, blank=True, db_constraint=False, related_name='clinic_id')
	def __str__(self):
		return self.username

class Token(models.Model):
	token_string = models.CharField(max_length=6)
	def __str__(self):
		return self.token_string

class Order(models.Model):
	owner_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_id')
	weight = models.DecimalField(max_digits=5, decimal_places=2)
	PRIORITY_CHOICES = (
		(1, 'High'),
		(2, 'Medium'),
		(3, 'Low'),
	)
	priority = models.IntegerField(
		choices=PRIORITY_CHOICES,
		default=1,
	)
	STATUS_CHOICES = (
		('QFP', 'Queued for Processing'),
		('PBW', 'Processing by Warehouse'),
		('QFD', 'Queued for Dispatch'),
		('DI', 'Dispatched'),
		('DE', 'Delivered'),
		('CA', 'Canceled')
	)
	status = models.CharField(
		max_length=3,
		choices=STATUS_CHOICES,
		default='QFP',
	)
	placing_time = models.DateTimeField()
	processing_time = models.DateTimeField(null=True, blank=True)
	processor_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, db_constraint=False, related_name='processor_id')
	dispatching_time = models.DateTimeField(null=True, blank=True)
	dispatcher_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, db_constraint=False, related_name='dispatcher_id')
	dilivered_time = models.DateTimeField(null=True, blank=True)
	canceled_time = models.DateTimeField(null=True, blank=True)
	destination_id = models.ForeignKey(Clinic, on_delete=models.CASCADE, null=True, blank=True, db_constraint=False, related_name='destination_id')
	def __str__(self):
		return f'{self.id}'# f'{self.placing_time} ({self.status})'

class Category(models.Model):
	category_name = models.CharField(max_length=50)
	def __str__(self):
		return self.category_name

class Item(models.Model):
	item_name = models.CharField(max_length=150)
	item_description = models.CharField(max_length=250)
	photo_url = models.CharField(max_length=200)
	weight = models.DecimalField(max_digits=5, decimal_places=2)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	def __str__(self):
		return self.item_name

class OrderContainsItem(models.Model):
	order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
	item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
	item_quantity = models.IntegerField()
	def __str__(self):
		return f'{self.order_id} ({self.item_id})'

class PriorityQueue(models.Model):
	order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
	def __str__(self):
		return f'{self.order_id}'

class DispatchQueue(models.Model):
	order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
	def __str__(self):
		return f'{self.order_id}'

class Distance(models.Model):
	source_clinic_id = models.ForeignKey(Clinic, on_delete=models.CASCADE, related_name='source_clinic_id')
	destination_clinic_id = models.ForeignKey(Clinic, on_delete=models.CASCADE, related_name='destination_clinic_id')
	distance = models.DecimalField(max_digits=5, decimal_places=2)
	def __str__(self):
		return f'{self.source_clinic_id} - {self.destination_clinic_id}'

	class Meta:
		unique_together = ('source_clinic_id', 'destination_clinic_id',)

jackas/asp/views.py
import itertools, csv, io, os, tsp, math
from django.contrib.auth.models import User as DjangoUser
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from datetime import datetime
from django.template import loader
from django.http import HttpResponseRedirect
from asp.models import User, Clinic, Token, Order, Item, OrderContainsItem, PriorityQueue, DispatchQueue, Category, Distance
from django.shortcuts import redirect
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.graphics import renderPDF
from django.core.mail import EmailMessage
from django.db.models import Q

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")

class HomePage(ListView):
	def get(self,request):
		template = loader.get_template('asp/homepage.html')
		num_user = len(User.objects.all())
		context = {
			'num_user': num_user
		}
		return HttpResponse(template.render(context, request))

class ViewHome(ListView):
	def get(self,request):
		userid = int(request.GET.get('id',None))
		role = request.GET.get('role',None)

		if role == 'CM':
			category_id = Category.objects.get(category_name='IV Fluids').pk
			return redirect('/asp/clinic_manager/'+str(userid)+'/home')
		elif role == 'D':
			return redirect('/asp/dispatcher/'+str(userid)+'/home')
		else:
			return redirect("/asp/warehouse_personnel/"+str(userid)+"/home")		

class PersonalHome(ListView):
	def get(self, request):

		name = request.user.username
		user = User.objects.get(username = name)
		userid = user.pk

		context = {}

		if user.role == 'CM':
			category_id = Category.objects.get(category_name='IV Fluids').pk
			return redirect('/asp/clinic_manager/'+str(userid)+'/home')
		elif user.role == 'D':
			return redirect('/asp/dispatcher/'+str(userid)+'/home')
		else:
			return redirect("/asp/warehouse_personnel/"+str(userid)+"/home")

class PersonalInfo(ListView):
	template_name = 'asp/personal_info.html'

	def get_queryset(self): 
		self.id = self.kwargs['id']
		return User.objects.filter(pk=self.id).all()

class ChangeInfo(ListView):
	def get(self, request):
		username = request.GET.get('username',None)

		firstname = request.GET.get('firstname',None)
		lastname = request.GET.get('lastname',None)
		email = request.GET.get('email',None)
		password = request.GET.get('password',None)

		target_user = User.objects.get(username=username)

		target_user.firstname = firstname
		target_user.lastname = lastname
		target_user.email = email

		django_user = DjangoUser.objects.get(username=target_user.username)

		django_user.first_name = firstname
		django_user.last_name = lastname
		django_user.email = email
		django_user.set_password(password)
		
		target_user.password = password

		target_user.save()

		django_user.save()
		return redirect('/asp/'+str(target_user.pk)+'/personal_info')


class CMConstructOrder(ListView):
	def get(self, request):
		num_order = int(request.GET.get('num',None))
		
		new_weight = float(request.GET.get('weight',None))
		new_priority = request.GET.get('priority',None)
		user_id = int(request.GET.get('user',None))

		new_order = Order()
		new_order.weight=new_weight
		new_order.priority=new_priority
		new_order.status='QFP'
		new_order.placing_time=datetime.now()

		user = User.objects.get(pk = user_id)

		new_order.destination_id = user.clinic_id
		new_order.owner_id = user

		new_order.save()

		queue = PriorityQueue()
		queue.order_id = new_order
		queue.save()

		item_list = []
		quantity_list = []
		photo_list = []

		for i in range(num_order):
			new_relation = OrderContainsItem()
			itemid = int(request.GET.get('item'+str(i),None))
			itemnum = int(request.GET.get('item'+str(i)+'num',None))

			item = Item.objects.get(pk=itemid)

			new_relation.order_id = new_order
			new_relation.item_id = item
			new_relation.item_quantity = itemnum

			item_list.append(item.item_name)
			quantity_list.append(itemnum)
			photo_list.append(item.photo_url)

			new_relation.save()

		template = loader.get_template('asp/view_order_info.html')
		context = {
			'num_order': num_order,
			'new_weight': new_weight,
			'new_priority': new_priority,
			'user_id': user_id,
			'item_list': item_list,
			'quantity_list': quantity_list,
			'photo_list': photo_list
		}
		return HttpResponse(template.render(context, request))


class CMViewItems(ListView):
	template_name = 'asp/cm_home.html'

	def get_queryset(self):
		categories = Category.objects.all()
		self.category = categories[0]
		return Item.objects.filter(category=self.category).all()

	def get_context_data(self, **kwargs): 
		self.id = self.kwargs['id'] 
		context = super().get_context_data(**kwargs) 
		context['user'] = User.objects.get(pk = self.id) 
		context['categories'] = Category.objects.all()
		categories = Category.objects.all()
		context['cat'] = categories[0]
		return context

class CMViewItemInfo(ListView):
	template_name = 'asp/view_item_info.html'
	def get_queryset(self):
		self.id = self.kwargs['id']
		return Item.objects.filter(pk = self.id).all()

class CMViewShippingLabel(ListView):
	def get(self, request, *args, **kwargs):
		response = HttpResponse(content_type='application/pdf')
		self.order_id = self.kwargs['id']
		order = Order.objects.get(pk=self.order_id)

		filename = "shipping_label-" + str(order.pk) + ".pdf"

		response['Content-Disposition'] = 'attachment; filename=' + filename
		
		Order_Item = OrderContainsItem.objects.all()

		destination = Clinic.objects.get(pk=order.destination_id.pk)
		p = canvas.Canvas(response)
		p.setTitle("Shipping Label - ASP")
		p.drawString(100, 800, 'OrderNumber: ' + str(order.pk))

		p.drawString(300, 800, 'Priority: ' + str(order.priority))
		p.drawString(100, 750, 'Order info:')
		length=730
		for elem in Order_Item:
			if elem.order_id == order:
				item_name = Item.objects.get(pk=elem.item_id.pk).item_name
				p.drawString(100, length, 'Item Name: ' + str(item_name)+'    Quantity: '+str(elem.item_quantity))
				length=length-20
		p.drawString(100, length-20, 'Destination: ' + str(destination.clinic_name))
		p.drawString(100, length-40, 'Address: '+str(destination.clinic_address))
		p.showPage()
		p.save()

		return response

class CMViewOrder(ListView):
	template_name = 'asp/view_order.html'

	def get_queryset(self):
		self.id = self.kwargs['id']

	def get_context_data(self, **kwargs): 
		context = super().get_context_data(**kwargs) 
		context['user'] = User.objects.get(pk = self.id)
		all_orders = Order.objects.filter(owner_id = context['user']).all()

		canceled_orders = [order for order in all_orders if order.status == 'CA']
		normal_orders = [order for order in all_orders if not order.status == 'CA']
		delivered_orders = [order for order in normal_orders if order.status == 'DE']
		processing_orders = [order for order in normal_orders if not order.status == 'DE']
		canceled_orders.extend(delivered_orders)

		for order in processing_orders:
			order.status = order.get_status_display()
			order.priority = order.get_priority_display()
		for order in canceled_orders:
			order.status = order.get_status_display()
			order.priority = order.get_priority_display()

		context['processing_orders'] = processing_orders
		context['other_orders'] = canceled_orders
		return context

class CMCancelOrder(ListView):
	def get(self, request, *args, **kwargs):
		self.id = kwargs['id']
		self.orderid = kwargs['orderid']
		order_to_update = Order.objects.get(id=self.orderid)
		order_to_update.status = 'CA'
		order_to_update.canceled_time = datetime.now()
		order_to_update.save()
		order_to_remove_from_queue = PriorityQueue.objects.get(order_id = order_to_update)
		order_to_remove_from_queue.delete()
		return redirect('/asp/clinic_manager/'+str(self.id)+'/view_order')

class CMConfirmOrder(ListView):
	def get(self, request, *args, **kwargs):
		self.id = kwargs['id']
		self.orderid = kwargs['orderid']
		order_to_update = Order.objects.get(id=self.orderid)
		order_to_update.status = 'DE'
		order_to_update.dilivered_time = datetime.now()
		order_to_update.save()
		return redirect('/asp/clinic_manager/'+str(self.id)+'/view_order')

class DispatcherViewQueue(ListView):
	template_name = 'asp/dispatch_queue_list.html'

	def get_queryset(self):
		self.id = self.kwargs['id']

	def get_context_data(self, **kwargs): 
		context = super().get_context_data(**kwargs) 
		context['user'] = User.objects.get(pk = self.id)
		queue_record_list = DispatchQueue.objects.all()
		order_list = [elem.order_id for elem in queue_record_list]
		for order in order_list:
			order.priority = order.get_priority_display()
		context['order_list'] = reorderQueue(order_list)
		return context

def calculatePackage(reordered_list):
	package = []
	total_weight = 0
	i = 0
	while total_weight <= 25 and i < len(reordered_list):
		package.append(reordered_list[i])
		total_weight += float(reordered_list[i].weight)
		i += 1
		if i >= len(reordered_list):
			break
		elif total_weight + float(reordered_list[i].weight) > 25:
			break	
	return package

class DispatcherViewPackage(ListView):
	template_name = 'asp/view_package.html'

	def get_queryset(self):
		self.id = self.kwargs['id']

	def get_context_data(self, **kwargs): 
		context = super().get_context_data(**kwargs) 
		context['user'] = User.objects.get(pk = self.id)
		queue_record_list = DispatchQueue.objects.all()
		order_list = [elem.order_id for elem in queue_record_list]
		reordered_list = reorderQueue(order_list)

		package = calculatePackage(reordered_list)
		total_weight = sum([elem.weight for elem in package])
		context['order_list'] = package
		context['total_weight'] = str(total_weight)
		return context

class DispatcherViewItinerary(ListView):
	def get(self, request):
		# generate package
		queue_record_list = DispatchQueue.objects.all()
		order_list = [elem.order_id for elem in queue_record_list]
		package = []
		total_weight = 0
		i = 0

jackas/asp/templates/asp/cm_home.html
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Clinic Manager Home Page</title>
  {% load static %}
  <link rel='stylesheet' href="{% static "stylesheets/mystyle.css" %}" type='text/css' >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body onload="initiateVar({{user.pk}},{{cat.category_name}})">
  <div id='header'>
    <span id='client_info'>Hello, {{user.username}} </span>

    <span id='website_title'>Supplies Available</span>
  </div>

  <div id='content'>
    
    <div id='personal' style='width: 20%'>

        <div style="margin-left: 40px;"><h3>Personal Info</h3></div>
        <div id='profile'>
            <div class='myButton' id='profile_btn'>
                {{user.username}}
            </div>
            <div class='myButton'>Role: Clinic Manager</div>
        </div>
        <hr style="border: 1px solid black;" />

        <ul id='personal_list' style='list-style-type: none'> 
            <li class='myButton'> 
              <a href="/asp/{{user.pk}}/personal_info" target="_blank">Personal Information</a>
            </li> 
            <li class='myButton'>
              <a href="" style="background-color: #adadad">Home</a>
            </li> 
            <li class='myButton'>
              <a href="/asp/clinic_manager/{{user.pk}}/view_order">View Orders</a>
            </li>
        </ul> 

      </div>

      <div id='side' style='width: 15%'>

        <h4 style="margin-left: 40px;">Category List</h4>
        <ul id='category_list' style='list-style-type: none; float: left;'> 
            {% for category in categories %} 
            <li class='myButton'>
              <a href="{{category.pk}}">
                {{ category.category_name }}
              </a>
            </li> 
            {% empty %} 
            <li>Categories not available.</li> 
            {% endfor %} 
        </ul> 

      </div>

      <div id='display' style='width: 60%'>

        <div id="cat" style="margin-left: 150px;">IV Fluids</div>

        <ul id='items_display' style='list-style-type: none'>
            {% for item in item_list %} 
          <li style='display: inline-block' id='{{item.pk}}'>
            {% load static %}
            <a href="http://127.0.0.1:8000/asp/clinic_manager/item_info/{{item.pk}}" target="_blank">
              <img src="{% static "" %}{{item.photo_url}}" class='myButton' >
            </a>           
            <p style="white-space: initial;">{{item.item_name}}</p>
            Quantity:
            <select id='quantity_list' onchange="updateOrder({{item.pk}},{{item.weight}},this.value)">
                {% for i in "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %}
                  <option value={{forloop.counter0}}>{{forloop.counter0}}</option>
                {% endfor %}
            </select>
          </li>
            {% empty %} 
            <li>Items not available.</li> 
            {% endfor %} 
        </ul>
    </div>

      <div id='foot' style="margin-left: 450px">

        <div id='current_cart'>
            <span> 
                Total weight: <input type="number" id="totalWeight" name="totalWeight" value="0" disabled style="width: 80px;" /> 
            </span>

            <span>
                 Maximum weight: <input id='maxWeight' type="number" name="maxWeight" value="23.8" disabled style="width: 80px;">
            </span>   

            <span id="warning"></span>       
        </div>

        <div id="construct_order" style="margin-top: 20px; margin-left: 100px;">
            Select priority:
            <select id='priority_list' style="width: 80px;">
                  <option value=1>High</option>
                  <option value=2>Medium</option>
                  <option value=3 selected>Low</option>
            </select>            
          <span id='construct' class='myButton' onclick="constructOrder({{user.pk}})"> Submit Order </span>
        </div>

      </div>

</div>

{% load static %}
<script src="{% static "javascripts/myscripts.js" %}" type="text/javascript">
</script>
  
</body>
</html>

jackas/asp/templates/asp/personal_info.html
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>View Personal Info</title>
  {% load static %}
  <link rel='stylesheet' href="{% static "stylesheets/mystyle.css" %}" type='text/css' >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<style>
  input {
    min-width: 500px;
  }
</style>
</head>

<body>
  <div id='header'>
    <span id='client_info'>Hello, {{user.username}} </span>

    <span id='website_title'>View Personal Info</span>
  </div>

  <div id='content'>
    
    <div id='personal' style='width: 20%'>

        <div style="margin-left: 40px;"><h3>Personal Info</h3></div>
        <div id='profile'>
            <div class='myButton' id='profile_btn'>
                {{user.username}}
            </div>
            {% for user in user_list %}
            <div class='myButton'>Role: {{user.role}}</div>
            {% endfor %}
        </div>
        <hr style="border: 1px solid black;" />

        <ul id='personal_list' style='list-style-type: none'> 
            <li class='myButton'> 
              <a href="" style="background-color: #adadad">Personal Information</a>
            </li> 
        </ul> 

      </div>

      <div id="side" style='width: 95%;'>

        <form action="/asp/change_info" method="GET">

        <ul style='list-style-type: none; font-size: x-large;' >

          {% for user in user_list %}
          <li style="margin-top: 20px;" onclick="cannotChange1(this)">
              Username: <input id="name" type="text" value="{{user.username}}" disabled > <span id="namemsg"></span>       
          </li>

          <li style="margin-top: 20px;">
              Password: <input name="password" type="password" value="{{user.password}}"> 
          </li>

          <li style="margin-top: 20px;">
              Firstname: <input type="text" name="firstname" value="{{user.firstname}}">       
          </li>

          <li style="margin-top: 20px;">
              Lastname: <input type="text" name="lastname" value="{{user.lastname}}">     
          </li>

          <li style="margin-top: 20px;">
              Email : <input type="text" name="email" value="{{user.email}}">     
          </li>

          <li style="margin-top: 20px;" onclick="cannotChange2(this)">
              Role : <input id="role" name="role"  type="text" value="{{user.role}}" disabled>  <span id="rolemsg"></span>
          </li>

          {% if user.clinic_id.clinic_name %}

          <li style="margin-top: 20px;" onclick="cannotChange3(this)">
              Clinic Name :  <input id="clinic_name" type="text" value="{{user.clinic_id.clinic_name}}" disabled > <span id="namemsg"></span>
          </li>  

          <li style="margin-top: 20px;" onclick="cannotChange4(this)">
              Clinic Address : <input id="clinic_addr" type="text" value="{{user.clinic_id.clinic_address}}" disabled > <span id="namemsg"></span>
          </li>    

          {% endif %}

          <li>
            <input type="hidden" name="username" value="{{user.username}}">
          </li>

          <li style="margin-top: 20px;" onclick="changeInfo(elem)">
             <input type="submit"> 
          </li>  

          {% endfor %}  

        </ul>

        </form>
      </div>

</div>
  
  <script>

  modified1 = false;
  modified2 = false;
  modified3 = false;
  modified4 = false;

  function cannotChange1(elem){
    if (!modified1){
      elem.innerHTML += "Cannot be changed!";
      modified1 = true;
    }
  }

  function cannotChange2(elem){
    if (!modified2){
      elem.innerHTML += "Cannot be changed!";
      modified2 = true;
    }
  }

  function cannotChange3(elem){
    if (!modified3){
      elem.innerHTML += "Cannot be changed!";
      modified3 = true;
    }
  }

  function cannotChange4(elem){
    if (!modified4){
      elem.innerHTML += "Cannot be changed!";
      modified4 = true;
    }
  }

  function viewHome(id,role){
    $('<form action="/asp/view_home" method="GET"/>')
        .append($('<input type="hidden" name="id" value="' + id + '">'))
        .append($('<input type="hidden" name="role" value="' + role + '">'))
        .appendTo($(document.body)) //it has to be added somewhere into the <body>
        .submit();
  }
</script>
</body>
</html>

jackas/asp/templates/asp/view_item_info.html
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>View Item Info</title>
  {% load static %}
  <link rel='stylesheet' href="{% static "stylesheets/mystyle.css" %}" type='text/css' >
</head>

<body>
  <div id='header'>

    <span id='website_title'>View Item Info</span>
  </div>

  <div id='content'>

        <table id='item_display' style='border-style: hidden; font-size: large; margin-top: 100px;'>

            <tr>
                <th align="center">Photo</th>
                <th align="center">Name</th> 
                <th align="center">Category</th>
                <th align="right">Description</th>
                <th align="right">Weight</th>
            </tr>

            {% for item in item_list %} 
          <tr id='{{item.pk}}'>
            {% load static %}

            <td>
              <img src="{% static "" %}{{item.photo_url}}" class='myButton' onclick='loadItemInfo(item)' >
            </td>

            <td>{{item.item_name}}</td>

            <td>{{item.category.category_name}}</td>

              <td>
              {{item.item_description}} 
              </td>

              <td>
                {{item.weight}}KG
              </td>

          </tr>
            {% empty %} 
            <tr>
              <td>Items not available.</td>
            </tr> 
            {% endfor %} 
        </ul>

</div>

{% load static %}
<script src="{% static "javascripts/myscripts.js" %}" type="text/javascript">
</script>
  
</body>
</html>